language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 4.2.6

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@3.5.2'
  - npm install -g npm@latest
  - npm install -g node@latest